development:
  adapter: sqlite3
  database: db/timeline_dev.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/timeline_test.sqlite3
  pool: 5
  timeout: 5000
  
production:
  adapter: sqlite3
  database: db/timeline_prod.sqlite3
  pool: 5
  timeout: 5000

